# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/3007/hdl
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/5c02/sources_1/imports/riscv-single
  } {
      /var/tmp/dwe_vivado_inst/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /var/tmp/dwe_vivado_inst/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /var/tmp/dwe_vivado_inst/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/3007/hdl
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/66be/hdl/verilog
    /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/ipshared/5c02/sources_1/imports/riscv-single
  } {
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_processing_system7_0_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_axi_bram_ctrl_0_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_axi_bram_ctrl_1_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_blk_mem_gen_0_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_rst_ps7_0_50M_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_axi_bram_ctrl_1_bram_0_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_axi_smc_2_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_rv_pl_0_1_stub.v
      ./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/realtime/design_1_axi_gpio_0_1_stub.v
      /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/synth/design_1.v
      /u/halle/dwe/home_at/Desktop/Test/Test.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib xpm /var/tmp/dwe_vivado_inst/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4078543-halle.cli.ito.cit.tum.de/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
